name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_Package_S3_Bucket_Name : " kostatestgithubactions "
  EB_Application_Name       : " elasticbeanstalk-us-east-2-766583418921 "
  EB_Environment_Name       : " elasticbeanstalk-us-east-2-766583418921-env "
  Deploy_Package_Name       : " Kosta_test_${{ github.sha }}.zip"
  AWS_Region_Name           : " us-east-2 "
on:
  push:
    branches: 
      -master
    
      
jobs: 
  Kosta-CI-part:
      runs-on: Windows-latest
      steps:
      - name: Git clone our repo      
        uses: actions/checkout@v2
        
        
      - name: Create ZIP deployment package
        run : zip -r ${{ env.Deploy_Package_Name }}./ -x *.git*
